apiVersion: v1
kind: ServiceAccount
metadata:
  name: guidebook-log-aggregator-serviceaccount
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: guidebook-log-aggregator-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec", "services"]
  verbs: ["events", "get", "watch", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create", "delete"]
#- apiGroups: ["apps"]
#  resources: [deployments]
#  verbs: [get, list]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: guidebook-log-aggregator-rolebinding
subjects:
- kind: ServiceAccount
  name: guidebook-log-aggregator-serviceaccount
roleRef:
  kind: Role
  name: guidebook-log-aggregator-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Pod
metadata:
  name: guidebook-log-aggregator
  labels:
    app: guidebook-log-aggregator
spec:
#      volumes:
#        - name: profile-volume
#          configMap:
#            name: profile-config
  restartPolicy: Never
  serviceAccountName: guidebook-log-aggregator-serviceaccount
  containers:
    - name: guidebook-log-aggregator
      image: ${LOG_AGGREGATOR_IMAGE-ghcr.io/project-codeflare/codeflare-log-aggregator:${LOG_AGGREGATOR_TAG-latest}}
      env:
        - name: QUIET_CONSOLE
          value: "true"
        - name: LOG_AGGREGATOR_POD_NAME
          value: guidebook-log-aggregator # TODO somehow share this with ./names.md
