apiVersion: v1
kind: ServiceAccount
metadata:
  name: ray-head-serviceaccount
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ray-head-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ray-head-rolebinding
subjects:
- kind: ServiceAccount
  name: ray-head-serviceaccount
roleRef:
  kind: Role
  name: ray-head-role
  apiGroup: rbac.authorization.k8s.io
