{{- if .Values.rbac.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ray.serviceaccount" . }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "ray.role" . }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ray.rolebinding" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "ray.serviceaccount" . }}
roleRef:
  kind: Role
  name: {{ include "ray.role" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
