apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Values.clusterName }}-jupyterlab
    labels:
        app: jupyterlab-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: jupyterlab-pod
    template:
        metadata:
            labels:
                app: jupyterlab-pod
        spec:
            restartPolicy: Always
            containers:
                - name: jupyterlab
                  image: {{ .Values.rayImage }}
                  command: ["/bin/bash", "-c", "--"]
                  args: ["conda install -c conda-forge vim; pip install jupyterlab jupyterlab-vim; ray start --address={{ .Values.clusterName }}-ray-head:{{ .Values.rayHeadPort }}; sleep infinity;"]
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 8888
