apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.clusterName }}-jupyterlab
    labels:
        app: jupyterlab-deployment
spec:
    ports:
        - port: 8888
          protocol: TCP
    selector:
        app: jupyterlab-pod
