apiVersion: v1
kind: Pod
metadata:
  labels:
    app: minio
  name: minio
spec:
  containers:
  - name: minio
    image: quay.io/minio/minio:latest
    command:
    - /bin/bash
    - -c
    args: 
    - minio server /data --console-address :9090
---
apiVersion: v1
kind: Service
metadata:
  name: minio-svc
spec:
  ports:
  - name: client
    protocol: TCP
    port: 9000
    targetPort: 9000
  - name: console
    protocol: TCP
    port: 9090
    targetPort: 9090
  selector:
    app: minio
  
