apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.s3.secret.name }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.s3.AWS_ACCESS_KEY_ID | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.s3.AWS_SECRET_ACCESS_KEY | b64enc }}
