name: basepython3
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2021.10.26
  - certifi=2021.5.30
  - cffi=1.14.6
  - charset-normalizer=2.0.4
  - conda=4.10.3
  - conda-package-handling=1.7.3
  - cryptography=35.0.0
  - cudatoolkit=11.3.1
  - dataclasses=0.8
  - ffmpeg=4.2.2
  - freetype=2.11.0
  - gmp=6.2.1
  - gnutls=3.6.15
  - idna=3.3
  - intel-openmp=2022.0.1
  - jpeg=9d
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libidn2=2.3.2
  - libopus=1.3.1
  - libpng=1.6.37
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuv=1.40.0
  - libvpx=1.7.0
  - libwebp-base=1.2.2
  - lz4-c=1.9.3
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - ncurses=6.3
  - nettle=3.7.3
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1m
  - pillow=8.3.1
  - pip=21.2.2
  - pycosat=0.6.3
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.6.13
  - pytorch=1.10.2
  - pytorch-mutex=1.0
  - readline=8.1.2
  - requests=2.27.1
  - ruamel_yaml=0.15.100
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.37.2
  - tk=8.6.11
  - torchaudio=0.10.2
  - torchvision=0.11.3
  - tqdm=4.62.3
  - typing_extensions=3.10.0.2
  - urllib3=1.26.8
  - wheel=0.37.1
  - x264=1!157.20191217
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - attrs==21.4.0
    - click==8.0.4
    - deprecated==1.2.13
    - filelock==3.4.1
    - grpcio==1.44.0
    - importlib-metadata==4.8.3
    - jsonschema==3.2.0
    - msgpack==1.0.3
    - packaging==21.3
    - protobuf==3.19.4
    - pyparsing==3.0.7
    - pyrsistent==0.18.0
    - pyyaml==6.0
    - ray==1.10.0
    - redis==4.1.4
    - wrapt==1.13.3
    - zipp==3.6.0
